Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and University of Bristol ID:

In [1]:
NAME = "Nathan Tozer"
UoB_ID = "ki18468"

---

# Homework 3

## Question 1

1. Create a function `gen_matrix1` that take $m,n\in\mathbb{N}$ as input and generate a $m\times n$ matrix (`numpy.array`) $A$ with entries $a_{ij}$, $0\le i\le m-1, 0\le j\le n-1$, with $a_{ij} = j \cdot m + i$.
1. Create a function `find_val1` that takes an $m\times n$ real-valued matrix $A=(a_{ij})$ that returns a 1D `numpy` array where the $i^{th}$ entry is the values amongst $a_{i1},\ldots,a_{in}$ that is closest to 5. Hint: you may find `numpy.argmin` useful, or another functionality of `numpy`.

In [2]:
# MANDATORY: Your functions need to be called gen_matrix1 and find_val1 exactly
# Parts 1 and 2

# YOUR CODE HERE
import numpy as np
import pandas as pd
import matplotlib as plt

# YOUR CODE HERE

#PART 1
def gen_matrix1(m,n):
    matrix = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            matrix[i,j] = j*m + i
    return matrix

#PART 2
def find_val1(M):
    vector = np.zeros((np.shape(M)[0],))
    minindex = np.argmin(abs(M-5), axis=1)
    for i in range(np.shape(M)[0]):
        vector[i] = M[i,minindex[i]]
    return vector

In [3]:
A = np.array([[0, 5, 10], [1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14]])

assert np.max(np.abs(gen_matrix1(5, 3)
                     - [[0, 5, 10], [1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14]])) < 1e-10


In [4]:
assert np.max(np.abs(find_val1(A) - np.array([5, 6, 7, 3, 4]))) < 1e-10


## Question 2

The data in `populations.txt` describes the populations of hares and lynxes (and carrots) in northern Canada from 1900 to 1920.

First, load the data into a `numpy` array and plot it.

Then compute and print, based on the data in `populations.txt`

1. Write a function `find_mean1` that takes `data` as input and outputs a `numpy.array` with the mean of each species. Write a nother function `find_std1` that takes `data` as input and outputs a `numpy.array` with the standard deviation of each species.

1. Write a function `find_year_max1` that takes `data` as input and outputs a `numpy.array` with the year when each species had the largest population.

1. Write a function `find_species_max1` that takes `data` as input and outputs a `numpy.array` of length 20 that outputs the name of species (`Hare`, `Lynx`, or `Carrot`) that has the largest population of that year.

1. Write a function `find_year_50000` that takes `data` as input and outputs a `numpy.array` consisting of years when any of the three populations (Hare, Lynx, or Carrot) is above 50000. (Hint: use `np.any`)


In [5]:
data = np.loadtxt("populations.txt")
print(data)

import matplotlib.pyplot as plt
plt.style.use("ggplot")
plt.plot(data[:,0], data[:,1], label="hare")
plt.plot(data[:,0], data[:,2], label="lynx")
plt.plot(data[:,0], data[:,3], label="carrot") 
plt.legend(("hare", "lynx", "carrot"))
plt.show()

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


<Figure size 640x480 with 1 Axes>

In [6]:
# Part 1

# YOUR CODE HERE
def column(M, i):
    return np.array([row[i] for row in M])

def find_mean1(data):
    mean = np.zeros((3,))
    for i in range(3):
        mean[i] = np.mean(column(data, i+1))
    return mean

In [7]:
assert np.max(np.abs(find_mean1(data)-np.array([34080, 20166, 42400]))) < 1


In [8]:
# Part 2
# YOUR CODE HERE
def find_std1(data):
    std = np.zeros((3,))
    for i in range(3):
        std[i] = np.std(column(data, i+1))
    return std

In [9]:
assert np.max(np.abs(find_std1(data)-np.array([20897, 16254, 3322]))) < 1


In [10]:
# Part 3

# YOUR CODE HERE
def find_year_max1(data):
    maxyear = np.zeros((3,))
    maxindex = np.argmax(data, axis=0)
    for i in range(3):
        maxyear[i] = data[maxindex[i+1],0]
    return maxyear

In [11]:
assert np.max(np.abs(find_year_max1(data)-np.array([1903, 1904, 1900]))) < 1e-10


In [12]:
# Part 4

# YOUR CODE HERE
def find_species_max1(data):
    maxanimal = ['']*21
    maxinyear = np.argmax(data, axis=1)
    for i in range(21):
        if maxinyear[i] == 1:
            maxanimal[i] = 'Hare'
        elif maxinyear[i] == 2:
            maxanimal[i] = 'Lynx'
        elif maxinyear[i] == 3:
            maxanimal[i] = 'Carrot'
    return np.array(maxanimal)

In [13]:
assert find_species_max1(data)[1] == "Carrot"
assert find_species_max1(data)[2] == "Hare"
assert find_species_max1(data)[-1] == "Carrot"


In [14]:
# Part 5

# YOUR CODE HERE
def find_year_50000(data):
    threshold = np.any(data > 50000, axis=1)
    abovefifty = []
    for i in range(21):
        if threshold[i]:
            abovefifty.append(column(data, 0)[i])
    return np.array(abovefifty)

find_year_50000(data)

array([1902., 1903., 1904., 1912., 1913., 1914., 1915.])

In [15]:
assert 1902 in find_year_50000(data)
assert 1913 in find_year_50000(data)


## Question 3

We analyse the file `chipo.csv`, which contains a list of food items ordered at a Mexican restaurant (yummy). Each order is identified by `order_id` and may consists of multiple items described by `item_name`, for which the total price is listed under `item_price` (i.e. this price is the per item price multiplied by the `quantity`).

We first read in the data file and drop the first column (which we do no need). We define the dataframe to be `df`.

1. The column `item_price` has a $\$$ sign in it. Strip the $\$$ sign from `item_price` and create a new column named `price` with `float64` as its datatype containing the numerical price. Write a function `convert_price` that takes `df` has input and outputs a dataframe that is the same with `df` but with an added column named `price`.

1. Write a function `find_order_spent` that takes `df` as input and outputs a `pandas.Series` object with `order_id` as index, and values of orders as values.

1. Write a function `find_avg_price_paid` that takes `df` as input and outputs a `pandas.Series` (not `numpy.array`) with `item_name` as index, and the average price paid by the customer for each item as the value. Note that due to choice items, the same item can have different prices. For example, Chicken Burrito can cost $\$ 8.49$ or $\$ 10.98$.


In [16]:
import numpy as np
import pandas as pd
df = pd.read_csv("chipo.csv")
df.drop(["Unnamed: 0", "choice_description"], axis=1, inplace=True)
print(df.head())
print('===========')
print(df.tail())
print('===========')
print(df.info())

   order_id  quantity                              item_name item_price
0         1         1           Chips and Fresh Tomato Salsa     $2.39 
1         1         1                                   Izze     $3.39 
2         1         1                       Nantucket Nectar     $3.39 
3         1         1  Chips and Tomatillo-Green Chili Salsa     $2.39 
4         2         2                           Chicken Bowl    $16.98 
      order_id  quantity           item_name item_price
4617      1833         1       Steak Burrito    $11.75 
4618      1833         1       Steak Burrito    $11.75 
4619      1834         1  Chicken Salad Bowl    $11.25 
4620      1834         1  Chicken Salad Bowl     $8.75 
4621      1834         1  Chicken Salad Bowl     $8.75 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 4 columns):
order_id      4622 non-null int64
quantity      4622 non-null int64
item_name     4622 non-null object
item_price    4622 non-

In [17]:
# Part 1

# YOUR CODE HERE
def convert_price(df):
    df["price"] = df.item_price.str.replace('$','').astype('float')
    return df

In [18]:
df1 = convert_price(df)
assert df1.dtypes["price"] == "float64"
assert np.abs(df1.price[0] - 2.39) < 1e-14


In [19]:
# Part 2
# YOUR CODE HERE
def find_order_spent(df):
    df1 = convert_price(df)
    return df1.groupby('order_id')['price'].sum()

In [20]:
order_spent = find_order_spent(df)
assert type(order_spent) is pd.core.series.Series
assert len(order_spent) == 1834
assert np.abs(np.max(order_spent) - 205.25) < 1e-14


In [21]:
# Part 3

# YOUR CODE HERE
def find_avg_price_paid(df):
    df1 = convert_price(df)
    rev = df1.groupby('item_name')['price'].sum()
    quantity = df1.groupby('item_name')['quantity'].sum()
    avg = rev/quantity
    return avg

In [22]:
avg_price = find_avg_price_paid(df)
assert type(avg_price) is pd.core.series.Series
assert abs(avg_price["Chicken Burrito"] - 9.43455) < 1e-5
assert len(avg_price) == 50

